---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-resource-quota
spec:
  hard:
    requests.memory: 1Gi
    limits.memory: 2Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: cpu-resource-quota
spec:
  hard:
    requests.cpu: "1"
    limits.cpu: "2"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: storage-resource-quota
spec:
  hard:
    requests.ephemeral-storage: 10G   # Logs also count
    limits.ephemeral-storage: 20G
    persistentvolumeclaims: "10"
    requests.storage: 10G
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: objects-resource-quota
spec:
  hard:
    pods: "20"
    replicationcontrollers: "20"
    configmaps: "10"
    secrets: "10"
    services: "10"
    # services.loadbalancers: "2"
    # services.nodeports: "0"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-counts-quota
spec:
  hard:
    count/configmaps: 20
    count/persistentvolumeclaims: 20
    count/jobs.batch: 20
    count/cronjobs.batch: 20
    count/secrets: 3
    count/services: 20
    count/replicationcontrollers: 20
    count/deployments.apps: 20
    count/deployments.extensions: 20
    count/replicasets.apps: 20
    count/statefulsets.apps: 20
