---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-resource-quota
spec:
  hard:
    requests.memory: 1Gi
    limits.memory: 2Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: cpu-resource-quota
spec:
  hard:
    requests.cpu: "1"
    limits.cpu: "2"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: objects-resource-quota
spec:
  hard:
    pods: "2"
    services: "10"
    replicationcontrollers: "20"
    configmaps: "10"
    secrets: "10"
    # services: "10"
    services.loadbalancers: "2"
    services.nodeports: "0"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: storage-resource-quota
spec:
  hard:
    limits.ephemeral-storage: 100G  # Logs also count
    requests.ephemeral-storage: 100G
    persistentvolumeclaims: "1"
    requests.storage: 100G
