---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:  # CNI=kindnetd
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 443
        hostPort: 4431
        listenAddress: "0.0.0.0"
        protocol: TCP
      - containerPort: 80
        hostPort: 8081
        listenAddress: "0.0.0.0"
        protocol: TCP
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 443
        hostPort: 4432
        listenAddress: "0.0.0.0"
        protocol: TCP
      - containerPort: 80
        hostPort: 8082
        listenAddress: "0.0.0.0"
        protocol: TCP
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 443
        hostPort: 4433
        listenAddress: "0.0.0.0"
        protocol: TCP
      - containerPort: 80
        hostPort: 8083
        listenAddress: "0.0.0.0"
        protocol: TCP
  - role: worker
  - role: worker
  - role: worker
