---
name: Terraform Test
on:
  pull_request:
    branches:
      - '**'
    paths:
      - .github/workflows/terraform.yml
      - Infra/AWS/Terraform/**
      - .checkov.yaml
  push:
    branches:
      - '**'
    paths:
      - .github/workflows/terraform.yml
      - Infra/AWS/Terraform/**
      - .checkov.yaml

jobs:
  terraform-test:
    runs-on: ubuntu-22.04
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.3
      - name: Terraform Init
        id: terraform-init
        run: |
          mkdir -p ./Infra/AWS/Terraform/plugins
          cd ./Infra/AWS/Terraform/modules/CP-SingleHost
          terraform providers mirror ../../plugins
          cd ../../../../..

          cd ./Infra/AWS/Terraform/
          for d in $(find ./modules -maxdepth 1 -mindepth 1 -type d| sort -n);do
            terraform -chdir=$d init -input=false -plugin-dir=../../plugins
          done

          cd ./components
          for d in $(find ./SingleHost -maxdepth 1 -mindepth 1 -type d | sort -n);do
            terraform -chdir=$d init -input=false -plugin-dir=../../../plugins
          done
      - name: Terraform fmt
        id: terraform-fmt
        run: |
          cd ./Infra/AWS/Terraform/
          for d in $(find ./modules  -maxdepth 1 -mindepth 1 -type d | sort -n);do
            terraform -chdir=$d fmt -check
          done

          cd ./components
          for d in $(find ./SingleHost  -maxdepth 1 -mindepth 1 -type d | sort -n);do
            terraform -chdir=$d fmt -check
          done

      - name: Terraform Validate
        id: terraform-validate
        run: |
          cd ./Infra/AWS/Terraform/
          for d in $(find ./modules  -maxdepth 1 -mindepth 1 -type d | sort -n);do
            terraform -chdir=$d validate -no-color .
          done

          cd ./components
          for d in $(find ./SingleHost  -maxdepth 1 -mindepth 1 -type d | sort -n);do
            terraform -chdir=$d validate -no-color .
          done

      - name: Install Terraform Lint
        id: install-terraform-lint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          cd Infra/AWS/Terraform/
          tflint --init -c ./.tflint.hcl

      - name: Terraform Lint
        id: terraform-lint
        run: |
          set -x
          cd ./Infra/AWS/Terraform/
          for d in $(find ./modules  -maxdepth 1 -mindepth 1 -type d | sort -n);do
            cd $d
            tflint -c ../../.tflint.hcl .
            cd ../..
          done

          cd ./components
          for d in $(find ./SingleHost  -maxdepth 1 -mindepth 1 -type d | sort -n);do
            cd $d
            tflint -c ../../../.tflint.hcl .
            cd ../..
          done

      - name: Install Terraform Sec
        id: install-terraform-sec
        run: |
          set -x
          wget https://github.com/aquasecurity/tfsec/releases/download/v1.21.0/tfsec-linux-amd64 -O ./Infra/AWS/Terraform/tfsec
          chmod +x ./Infra/AWS/Terraform/tfsec
          #go install github.com/aquasecurity/tfsec/cmd/tfsec@latest

      - name: Terraform Sec
        id: terraform-sec
        run: |
          set -x
          cd ./Infra/AWS/Terraform
          ./tfsec . --config-file ./tfsec.yml --force-all-dirs

      - name: tfsec
        uses: aquasecurity/tfsec-sarif-action@v0.1.0
        with:
          # working_directory: Infra/AWS/Terraform
          config_file: ./Infra/AWS/Terraform/.tflint.hcl
          # sarif_file: tfsec.sarif
          full_repo_scan: true

      - name: Upload TfSec SARIF file
        uses: actions/upload-artifact@v3
        with:
          name: tfsec.sarif
          path: tfsec.sarif

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9.14 # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: x64

      - name: Checkov Manual Run
        id: checkov-manual
        run: |
          set -x
          pip install checkov
          checkov -d . --config-file ./.checkov.yaml

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          config_file: .checkov.yaml
          output_format: sarif
          quiet: false

      - name: Upload Checkov SARIF file
        uses: actions/upload-artifact@v3
        with:
          name: checkov.sarif
          path: results.sarif
